version: "3.8"

services:
  mongo:
    image: "mongo:4.4"
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  gin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: go_to_line
    ports:
      - "8080:8080"